  version: "3.9"
  services:
    db:
      image: mysql:8
      environment:
        - MYSQL_ROOT_PASSWORD=minhasenha
        - MYSQL_DATABASE=ibge
        - MYSQL_USER=diego
        - MYSQL_PASSWORD=minhasenha
        - DB_HOST=db
      ports:
        - "3306:3306"
      volumes:
        - db_data:/var/lib/mysql

    app:
      build: .
      depends_on:
        - db
      environment:      
        - POSTGIS_CONNECTION_STRING=mysql+pymysql://diego:minhasenha@db:3306/ibge    
      restart: "no"
      ports:
        - "8000:8000"

  volumes:
    db_data:
